name: Test Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY_IMAGE: airdata/ansible-in-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - 
          name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
              name=ghcr.io/${{ env.REGISTRY_IMAGE }}
              name=${{ env.REGISTRY_IMAGE }}
            tags: |
              type=schedule
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=sha
            labels: |
              maintainer=Airdata Edition
              org.opencontainers.image.title=ansible-in-docker
              org.opencontainers.image.description=Ansible
              org.opencontainers.image.vendor=Airdata Corp.

        - 
          name: Inspect image
          run: |
            docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
